# Generated by Django 4.2.16 on 2024-10-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
    ]
