# Generated by Django 4.2.16 on 2024-11-03 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('guests', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('12:30pm', '12:30pm'), ('1:00pm', '1:00pm'), ('1:30pm', '1:30pm'), ('2:00pm', '2:00pm'), ('2:30pm', '2:30pm'), ('3:00pm', '3:00pm'), ('3:30pm', '3:30pm'), ('4:00pm', '4:00pm'), ('4:30pm', '4:30pm'), ('5:00pm', '5:00pm'), ('5:30pm', '5:30pm'), ('6:00pm', '6:00pm'), ('6:30pm', '6:30pm'), ('7:00pm', '7:00pm'), ('7:30pm', '7:30pm'), ('8:00pm', '8:00pm'), ('8:30pm', '8:30pm'), ('9:00pm', '9:00pm'), ('9:30pm', '9:30pm')], default='2:30pm')),
                ('message', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed')], default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
