# Generated by Django 4.2.16 on 2024-11-04 16:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_date',
            field=models.DateField(help_text='Please enter the date in this format dd/mm/yyyy', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
