# Generated by Django 4.2.16 on 2024-11-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
