# Generated by Django 4.2.16 on 2024-11-04 17:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingrequest_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_date',
            field=models.DateField(help_text='Please enter the date in this format yyyy-mm-dd', validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
