# Generated by Django 4.2.16 on 2024-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookingrequest_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_time',
            field=models.CharField(choices=[('12:30pm', '12:30pm'), ('1:00pm', '1:00pm'), ('1:30pm', '1:30pm'), ('2:00pm', '2:00pm'), ('2:30pm', '2:30pm'), ('3:00pm', '3:00pm'), ('3:30pm', '3:30pm'), ('4:00pm', '4:00pm'), ('4:30pm', '4:30pm'), ('5:00pm', '5:00pm'), ('5:30pm', '5:30pm'), ('6:00pm', '6:00pm'), ('6:30pm', '6:30pm'), ('7:00pm', '7:00pm'), ('7:30pm', '7:30pm'), ('8:00pm', '8:00pm'), ('8:30pm', '8:30pm'), ('9:00pm', '9:00pm'), ('9:30pm', '9:30pm')], default='2:30pm', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2, max_length=10),
        ),
    ]
