# Generated by Django 4.2.16 on 2024-11-02 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='BookingRequest',
        ),
    ]
