# Generated by Django 4.2.16 on 2024-11-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_bookingrequest_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='phone',
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=2),
        ),
    ]
